//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете язык .
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кликните здесь чтоб войти.
        /// </summary>
        public static string ConfMailLinkText {
            get {
                return ResourceManager.GetString("ConfMailLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодарим вас за подтверждение вашей электронной почты. пожалуйста .
        /// </summary>
        public static string ConfMailText {
            get {
                return ResourceManager.GetString("ConfMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение электронного адреса .
        /// </summary>
        public static string ConfMailTitle {
            get {
                return ResourceManager.GetString("ConfMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите новый пароль.
        /// </summary>
        public static string ConfNewPass {
            get {
                return ResourceManager.GetString("ConfNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль и пароль подтверждения не совпадают..
        /// </summary>
        public static string ConfNewPassErr {
            get {
                return ResourceManager.GetString("ConfNewPassErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateBut {
            get {
                return ResourceManager.GetString("CreateBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отфильтровать.
        /// </summary>
        public static string CreateButFilter {
            get {
                return ResourceManager.GetString("CreateButFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string CreateLinkDelete {
            get {
                return ResourceManager.GetString("CreateLinkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробная информация.
        /// </summary>
        public static string CreateLinkDetails {
            get {
                return ResourceManager.GetString("CreateLinkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string CreateLinkEdit {
            get {
                return ResourceManager.GetString("CreateLinkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить макер.
        /// </summary>
        public static string CreateMapButDel {
            get {
                return ResourceManager.GetString("CreateMapButDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите на карту, чтобы добавить маркер..
        /// </summary>
        public static string CreateMapTitle {
            get {
                return ResourceManager.GetString("CreateMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать Новую Задачу.
        /// </summary>
        public static string CreateNewLink {
            get {
                return ResourceManager.GetString("CreateNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите дату.
        /// </summary>
        public static string CreateSelectDate {
            get {
                return ResourceManager.GetString("CreateSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание новой задачи.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль.
        /// </summary>
        public static string CurrentPass {
            get {
                return ResourceManager.GetString("CurrentPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверенны что хотите удалить это задание?.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробная информация.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На указанный электронный адрес отправлены дальнейшие инструкции по завершению регистрации..
        /// </summary>
        public static string DispleyEmailText {
            get {
                return ResourceManager.GetString("DispleyEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string EditButSave {
            get {
                return ResourceManager.GetString("EditButSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эл. адрес.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время обработки Вашего запроса произошла ошибка..
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить ссылку на почту.
        /// </summary>
        public static string ForgPassButt {
            get {
                return ResourceManager.GetString("ForgPassButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте свой адрес электронной почты, чтобы сбросить пароль..
        /// </summary>
        public static string ForgPassConfText {
            get {
                return ResourceManager.GetString("ForgPassConfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите адрес электронной почты..
        /// </summary>
        public static string ForgPassText {
            get {
                return ResourceManager.GetString("ForgPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль ?.
        /// </summary>
        public static string ForgPassTitle {
            get {
                return ResourceManager.GetString("ForgPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заданий .
        /// </summary>
        public static string HaveTasks {
            get {
                return ResourceManager.GetString("HaveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователей.
        /// </summary>
        public static string HaveUsers {
            get {
                return ResourceManager.GetString("HaveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуй .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта учетная запись заблокирована, повторите попытку позже..
        /// </summary>
        public static string LockedOutText {
            get {
                return ResourceManager.GetString("LockedOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досступ закрыт.
        /// </summary>
        public static string LockedOutTitle {
            get {
                return ResourceManager.GetString("LockedOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string LoginForgot {
            get {
                return ResourceManager.GetString("LoginForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать нового пользователя.
        /// </summary>
        public static string LoginRegisterAsANewUser {
            get {
                return ResourceManager.GetString("LoginRegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используйте учетную запись для входа в систему..
        /// </summary>
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ManageIndLink {
            get {
                return ResourceManager.GetString("ManageIndLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль успешно изменен..
        /// </summary>
        public static string ManageIndSecss {
            get {
                return ResourceManager.GetString("ManageIndSecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение настроек учетной записи.
        /// </summary>
        public static string ManageIndText {
            get {
                return ResourceManager.GetString("ManageIndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string ManageIndTitle {
            get {
                return ResourceManager.GetString("ManageIndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широта.
        /// </summary>
        public static string MapLat {
            get {
                return ResourceManager.GetString("MapLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта &quot;Долгота&quot; Неправильное значение.
        /// </summary>
        public static string MapLatErr {
            get {
                return ResourceManager.GetString("MapLatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгота.
        /// </summary>
        public static string Maplng {
            get {
                return ResourceManager.GetString("Maplng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта &quot;Широта&quot; Неправильное значение.
        /// </summary>
        public static string MaplngErr {
            get {
                return ResourceManager.GetString("MaplngErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tочка на карте.
        /// </summary>
        public static string MapPoin {
            get {
                return ResourceManager.GetString("MapPoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок точки.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время вашей сессии закончено, и у вас нет необходимых куки. Для дальнейшей правильной работы войдите в систему..
        /// </summary>
        public static string NeedLoginText {
            get {
                return ResourceManager.GetString("NeedLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно зайти еще раз в учетную запись.
        /// </summary>
        public static string NeedLoginTitle {
            get {
                return ResourceManager.GetString("NeedLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не подтвержден.
        /// </summary>
        public static string NotConfirmedEmail {
            get {
                return ResourceManager.GetString("NotConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string RegComments {
            get {
                return ResourceManager.GetString("RegComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина поля &quot;Коментарии&quot; не может превышать 100 символов..
        /// </summary>
        public static string RegCommentsLen {
            get {
                return ResourceManager.GetString("RegCommentsLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string RegConfirmPassword {
            get {
                return ResourceManager.GetString("RegConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля не совпадают..
        /// </summary>
        public static string RegConfirmPasswordErr {
            get {
                return ResourceManager.GetString("RegConfirmPasswordErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового аккаунта..
        /// </summary>
        public static string RegCreate {
            get {
                return ResourceManager.GetString("RegCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string RegName {
            get {
                return ResourceManager.GetString("RegName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина поля &quot;Имя&quot; не может превышать 100 символов..
        /// </summary>
        public static string RegNameLen {
            get {
                return ResourceManager.GetString("RegNameLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина пароля должна быть не менее 6 символов..
        /// </summary>
        public static string RegPasswordLen {
            get {
                return ResourceManager.GetString("RegPasswordLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string RegPatronymic {
            get {
                return ResourceManager.GetString("RegPatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина поля &quot;Отчество&quot; не может превышать 100 символов..
        /// </summary>
        public static string RegPatronymicLen {
            get {
                return ResourceManager.GetString("RegPatronymicLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string RegPhone {
            get {
                return ResourceManager.GetString("RegPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string RegSurname {
            get {
                return ResourceManager.GetString("RegSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина поля &quot;Фамилия&quot; не может превышать 100 символов..
        /// </summary>
        public static string RegSurnameLen {
            get {
                return ResourceManager.GetString("RegSurnameLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня?.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string ResetPassButt {
            get {
                return ResourceManager.GetString("ResetPassButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кликните здесь чтоб войти.
        /// </summary>
        public static string ResetPassConfLink {
            get {
                return ResourceManager.GetString("ResetPassConfLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был сброшен. пожалуйста.
        /// </summary>
        public static string ResetPassConfText {
            get {
                return ResourceManager.GetString("ResetPassConfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установите новый пароль..
        /// </summary>
        public static string ResetPassText {
            get {
                return ResourceManager.GetString("ResetPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassTitle {
            get {
                return ResourceManager.GetString("ResetPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменена.
        /// </summary>
        public static string StatusAbolished {
            get {
                return ResourceManager.GetString("StatusAbolished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнена.
        /// </summary>
        public static string StatusAccomplished {
            get {
                return ResourceManager.GetString("StatusAccomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выполнена.
        /// </summary>
        public static string StatusNotImplemented {
            get {
                return ResourceManager.GetString("StatusNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ожидании.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string TaskDate {
            get {
                return ResourceManager.GetString("TaskDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата недействительна, введите год 1900- 3000.
        /// </summary>
        public static string TaskDateErr {
            get {
                return ResourceManager.GetString("TaskDateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание задачи.
        /// </summary>
        public static string Taskdescription {
            get {
                return ResourceManager.GetString("Taskdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина поля &quot;Описание задачи&quot; не может превышать 1000 символов..
        /// </summary>
        public static string TaskdescriptionErr {
            get {
                return ResourceManager.GetString("TaskdescriptionErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используется карта.
        /// </summary>
        public static string TaskIndexMap {
            get {
                return ResourceManager.GetString("TaskIndexMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string TaskTime {
            get {
                return ResourceManager.GetString("TaskTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание задачи.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная длина поля &quot;Краткое описание задачи&quot; не может превышать 100 символов..
        /// </summary>
        public static string TaskTitleErr {
            get {
                return ResourceManager.GetString("TaskTitleErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я хочу использовать карту.
        /// </summary>
        public static string UseMap {
            get {
                return ResourceManager.GetString("UseMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все задачи.
        /// </summary>
        public static string UsTaskIndexAll {
            get {
                return ResourceManager.GetString("UsTaskIndexAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web приложение.
        /// </summary>
        public static string WebApplication {
            get {
                return ResourceManager.GetString("WebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный логин или пароль.
        /// </summary>
        public static string WrongLogPass {
            get {
                return ResourceManager.GetString("WrongLogPass", resourceCulture);
            }
        }
    }
}
